### PR TITLE
Handle created dates not in ISO8601

### LINKED ISSUE #4398: Invalid imported created date
## Backtrace

    line 167 of [PROJECT_ROOT]/app/resources/scanned_resources/scanned_resource_decorator.rb: parse
    line 167 of [PROJECT_ROOT]/app/resources/scanned_resources/scanned_resource_decorator.rb: block in imported_created
    line 167 of [PROJECT_ROOT]/app/resources/scanned_resources/scanned_resource_decorator.rb: map

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/74574768)

https://figgy.princeton.edu/concern/scanned_resources/87381149-1840-4fe4-a3b3-d717011fbfb9/edit
Related to: https://github.com/pulibrary/pulfalight/pull/627

### PR DESCRIPTION
**Pull request by tpendragon**
Closes #4398

### CODE REVIEW

File: app/resources/scanned_resources/scanned_resource_decorator.rb [hunk 1]
```diff
@@ -164,7 +164,16 @@ def imported_created
...
+    output.map do |date|
+      date_string(date)
+    end
+  end
+
+  def date_string(date)
+    Date.parse(date.to_s).strftime("%B %-d, %Y")
+  rescue ArgumentError
+    # When the date's not ISO8601, just display it as-is.
+    date
```
Comment (jrgriffiniii) [inline app/resources/scanned_resources/scanned_resource_decorator.rb:176]: 👍

**Review by jrgriffiniii — APPROVED** [review]
