### PR TITLE
Fix monogram selector

### LINKED ISSUE #5162: Bootstrap 4: Fix Monograms
- Vue code in numismatics issue page isn't working.

https://github.com/pulibrary/figgy/pull/5158/commits/c6834b40daee7339930ce1579cd117b2ae406f50#diff-8f8a839652b55c4525ebfedb6bada1f85e3d3952fa9e9ffc99259510142e0ed7R346

### PR DESCRIPTION
**Pull request by eliotjordan**
Closes #5162 
Screen Shot 2022-06-16 at 11 14 35 AM

### CODE REVIEW

File: spec/models/numismatics/issues_feature_spec.rb [hunk 1]
```diff
@@ -346,28 +346,13 @@
...
-      issue_monogram_element = issue_monogram_elements.first
-      attributes = JSON.parse(issue_monogram_element[":members"])
-      expect(attributes).to be_a Array
-      expect(attributes.length).to eq(2)
-
-      first_attribute = attributes.first
-      expect(first_attribute.keys).to include("id", "url", "thumbnail", "title", "attached")
-      expect(first_attribute["id"]).to eq(monogram2.id.to_s)
-      expect(first_attribute["title"]).to eq("Test Monogram")
-      expect(first_attribute["attached"]).to be true
```
Comment (hackartisan) [inline spec/models/numismatics/issues_feature_spec.rb:363]: The test used to ensure that one was attached and one wasn't. Is that not important?

**Review by hackartisan — CHANGES_REQUESTED** [review]

File: spec/models/numismatics/issues_feature_spec.rb (hunk 1 above)
Comment (eliotjordan) [reply spec/models/numismatics/issues_feature_spec.rb:363]: Probably is. Fixed.
