### PR TITLE
Fix GeoBlacklight titles for imported scanned maps

### LINKED ISSUE #1725: GeoBlacklight documents can't generate title for ScannedMaps with imported metadata
The GeoBlacklight document generator can't generate a title for scanned maps where the metadata is imported from Voyager. This used to work fine.

### PR DESCRIPTION
**Pull request by eliotjordan**
Closes #1725

### CODE REVIEW

File: app/services/geo_discovery/document_builder/basic_metadata_builder.rb [hunk 1]
```diff
@@ -80,7 +80,10 @@ def subject
         # Use the standard resource decorator to retreive title.
         # @return [String] title
         def title
-          resource_decorator.model.decorate.title.try(:first)
+          # This convoluted set ot method calls is required because, in this case, we need the
+          # actual model decorator rather than the geoblacklight metadata decorator.
+          decorated_title = resource_decorator.model.decorate.title.try(:first)
```
Comment (jrgriffiniii) [inline app/services/geo_discovery/document_builder/basic_metadata_builder.rb]: That's odd, from what I would assume, this would just be delegated to the underlying resource decorator:
https://github.com/pulibrary/figgy/blob/master/app/services/geo_discovery/document_builder.rb#L31

Comment (jrgriffiniii) [reply app/services/geo_discovery/document_builder/basic_metadata_builder.rb]: Perhaps this is just related to my misunderstanding of https://github.com/pulibrary/figgy/blob/master/app/decorators/geoblacklight_metadata_decorator.rb#L20
