### PR TITLE
Handle empty nested resources when flattening manifests

### LINKED ISSUE #6787: [Figgy/production] NoMethodError: undefined method `id' for nil:NilClass
## Backtrace

    line 163 of [PROJECT_ROOT]/app/services/manifest_builder.rb: flattened_range_work_structure
    line 151 of [PROJECT_ROOT]/app/services/manifest_builder.rb: block in flattened_ranges
    line 148 of [PROJECT_ROOT]/app/services/manifest_builder.rb: map

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/122908233)

### PR DESCRIPTION
**Pull request by eliotjordan**
Closes #6787 

- **Add openssl gem explicitly to address cert failures**
  -  See: https://github.com/rails/rails/issues/55886#issuecomment-3393111414
- **Handle empty nested resources when flattening manifests**

### CODE REVIEW

File: spec/services/manifest_builder/by_resource_type/manifest_builder_scanned_resource_spec.rb [hunk 1]
```diff
@@ -276,7 +278,7 @@ def logical_structure(file_set_id)
       expect(output["sequences"][0]["canvases"].length).to eq 4
 
       # Two ranges at top level pointing to the parts.
```
Comment (hackartisan) [inline spec/services/manifest_builder/by_resource_type/manifest_builder_scanned_resource_spec.rb]: update this comment?

Comment (eliotjordan) [reply spec/services/manifest_builder/by_resource_type/manifest_builder_scanned_resource_spec.rb]: Done.

File: spec/services/manifest_builder/by_resource_type/manifest_builder_scanned_resource_spec.rb [hunk 2]
```diff
@@ -251,16 +251,18 @@ def logical_structure(file_set_id)
     end
   end
 
-  context "when given a deeply nested serial resource with PDFs", run_real_characterization: true do
+  context "when given a deeply nested serial resource with PDFs and empty resource members", run_real_characterization: true do
```
[the remark this answers is not in the document]
Comment (hackartisan) [reply spec/services/manifest_builder/by_resource_type/manifest_builder_scanned_resource_spec.rb]: Ah I see. There are just more resources now in the same test. 👍🏻

**Review by hackartisan — DISMISSED** [review]

**Review by hackartisan — APPROVED** [review]
