### PR TITLE
Archival Media Collections should parse barcodes from EAD

### LINKED ISSUE #4538: Archival Media Bag Ingest is Broken
Everything gets ingested into [Unorganized Barcodes] because `RemoteRecord` now returns a JSON summary from Pulfalight rather than the full EAD content. The spec's stub is bad.

See https://github.com/pulibrary/figgy/blob/42839d833bb097f7ecac54e57c739806ed9aecf3/spec/models/archival_media_bag_parser_spec.rb#L10

### PR DESCRIPTION
**Pull request by tpendragon**
This broke in the move to Pulfalight because we started parsing JSON
rather than the EAD itself. This pulls the EAD from Pulfalight and uses
that instead, and fixes the relevant tests.

Closes #4538

### CODE REVIEW

File: app/services/pul_metadata_services/client.rb [hunk 1]
```diff
@@ -27,6 +27,13 @@ def retrieve_from_aspace_pulfa(id)
         response.body.dup.force_encoding("UTF-8")
       end
 
+      def retrieve_aspace_pulfa_ead(id)
+        conn = Faraday.new(url: "https://findingaids-beta.princeton.edu/catalog/")
```
Comment (tpendragon) [inline app/services/pul_metadata_services/client.rb:31]: I'm leaving this findingaids-beta for now because fixing this across the code base will be a much bigger undertaking I just don't have time for right now.

Comment (eliotjordan) [reply app/services/pul_metadata_services/client.rb:31]: You're leaving the `retrieve_from_pulfa` method. I assume this is being used elsewhere and will be updated at a later date?

File: spec/services/pul_metadata_services/pulfa_record/media_resource_attributes_spec.rb [hunk 2]
```diff
@@ -1,14 +0,0 @@
...
-require "rails_helper"
-
-describe PulMetadataServices::PulfaRecord::MediaResourceAttributes do
-  subject(:media_resource_attributes) { described_class.new(data) }
-  let(:source) { file_fixture("pulfa/C0652/c0377.xml").read }
-  let(:data) { Nokogiri::XML(source).remove_namespaces! }
-
-  describe "#title" do
-    it "extracts the title value for media resource metadata" do
-      expect(media_resource_attributes.title).to eq ["Emir Rodriguez Monegal Papers"]
```
Comment (hackartisan) [inline spec/services/pul_metadata_services/pulfa_record/media_resource_attributes_spec.rb:11]: Were there other tests ensuring we got the desired title?

**Review by hackartisan — CHANGES_REQUESTED** [review]

File: spec/support/stub_bibdata.rb [hunk 3]
```diff
@@ -93,6 +93,16 @@ def stub_aspace(pulfa_id:, body: nil)
         },
         body: body || file_fixture("pulfa/aspace/#{pulfa_id}.json").read
       )
+    ead = Pathname.new(file_fixture_path).join("pulfa/aspace/#{pulfa_id}.ead.xml")
+    return unless File.exist?(ead)
+    stub_request(:get, "#{aspace_domain}/catalog/#{pulfa_id.tr('.', '-')}.xml")
+      .to_return(
+        status: 200,
+        headers: {
+          "Content-Type" => "application/json"
```
Comment (eliotjordan) [inline spec/support/stub_bibdata.rb:102]: Should be `application/xml`

**Review by eliotjordan — CHANGES_REQUESTED** [review]

File: app/services/pul_metadata_services/client.rb (hunk 1 above)
Comment (tpendragon) [reply app/services/pul_metadata_services/client.rb:31]: Yes, it's being used in tests right now. It'll get removed later.

File: spec/services/pul_metadata_services/pulfa_record/media_resource_attributes_spec.rb (hunk 2 above)
Comment (tpendragon) [reply spec/services/pul_metadata_services/pulfa_record/media_resource_attributes_spec.rb:11]: See commit message for second commit. Basically the logic for this was backwards according to a comment, and it doesn't make sense either - there's no reason to grab the collection title instead of the component title.

File: spec/support/stub_bibdata.rb (hunk 3 above)
Comment (tpendragon) [reply spec/support/stub_bibdata.rb]: Fixed.

File: spec/services/pul_metadata_services/pulfa_record/media_resource_attributes_spec.rb (hunk 2 above)
Comment (hackartisan) [reply spec/services/pul_metadata_services/pulfa_record/media_resource_attributes_spec.rb:11]: 👍🏻 @tpendragon pointed me at a test that checks for the desired title: https://github.com/pulibrary/figgy/blob/2a145c62ab8847f31a3b576b97d9f63d7a725354/spec/jobs/ingest_archival_media_bag_job_spec.rb#L264-L279

**Review by hackartisan — APPROVED** [review]
