### PR TITLE
Don't use buffered persister in CharacterizationJob so error messages are saved

### LINKED ISSUE #6059: Characterization failures should record an error_message on FileSets.
When things fail characterization they never leave processing and likely will never succeed, and the derivative health report should show that it's failed so they'll know they should reingest that item.

Right now some characterizers error and some ignore them (imagemagick.) Characterizers only have persisters, not ChangeSetPersisters, and the code in there is odd (it has instance methods that change their return value based on an instance variable that changes in a loop.)

### PR DESCRIPTION
**Pull request by eliotjordan**
- Characterization failure messages were not being saved on the FileSet when run in production. The issue was the buffered persister which rolled back once the job errored.

- Also removes troublesome and unnecessary ExternalMetadataService test. 

Closes #6059 

Working in staging:
Screenshot 2024-01-18 at 1 38 21 PM

### CODE REVIEW

File: spec/derivative_services/external_metadata_derivative_service_spec.rb [hunk 1]
```diff
@@ -46,16 +46,9 @@
     end
   end
 
-  before do
-    allow(EventGenerator::GeoblacklightEventGenerator).to receive(:new).and_return(event_generator)
-    allow(event_generator).to receive(:record_updated)
-  end
-
-  it "extracts metadata from the file into the parent resource and triggers an update event", rabbit_stubbed: true do
+  it "extracts metadata from the file into the parent resource", rabbit_stubbed: true do
```
Comment (hackartisan) [inline spec/derivative_services/external_metadata_derivative_service_spec.rb:49]: Do we still need rabbit_stubbed?

**Review by hackartisan — CHANGES_REQUESTED** [review]

File: spec/derivative_services/external_metadata_derivative_service_spec.rb (hunk 1 above)
Comment (eliotjordan) [reply spec/derivative_services/external_metadata_derivative_service_spec.rb]: Nope. Good catch. Pushed up the change.

**Review by hackartisan — APPROVED** [review]

**Comment by hackartisan** [comment]
I don't totally understand why we wanted the buffered persister to begin with. @tpendragon do you have insight on this?

**Comment by tpendragon** [comment]
> I don't totally understand why we wanted the buffered persister to begin with. @tpendragon do you have insight on this?

It's probably copied from the derivative service, which had a buffer so it'd have a transaction and if the second derivative service failed it'd roll back the first one. In the case of characterization I don't think we ever use two at once?
