### PR TITLE
Handles Valkyrie::Persistence::StaleObjectErrors during Resource updates

### LINKED ISSUE #2970: State/Visibility Propagation Caused StaleObjectError
To the user, all he did was try to edit an object to have a new collection and got a "something went wrong" page. What actually happened was saving that object propagated state/visibility (maybe FileSets didn't have their visibility set right?), and one of them had just finished being characterized.

### PR DESCRIPTION
**Pull request by jrgriffiniii**
Ensures that when `Valkyrie::Persistence::StaleObjectErrors` are raised while attempting to update a resource, users are redirected to the edit view and alerted with a warning message.  Resolves #2970

### CODE REVIEW

File: app/controllers/concerns/resource_controller.rb [hunk 1]
```diff
@@ -79,8 +79,11 @@ def update
     else
       after_update_failure
     end
-  rescue Valkyrie::Persistence::ObjectNotFoundError => e
-    after_update_error e
+  rescue Valkyrie::Persistence::ObjectNotFoundError => not_found_error
+    after_update_error not_found_error
+  rescue Valkyrie::Persistence::StaleObjectError
+    flash[:alert] = "Sorry, another user updated this resource simultaneously.  Please resubmit your changes."
```
Comment (hackmastera) [inline app/controllers/concerns/resource_controller.rb]: Maybe "user or process"?
