### PR TITLE
Disable share/download for CDL enabled items.

### LINKED ISSUE #4134: Don't show Share or IIIF widgets in CDL viewer
These will not work correctly with CDL content, so we should not show them.

### PR DESCRIPTION
**Pull request by tpendragon**
Closes #4134

### CODE REVIEW

File: app/controllers/application_controller.rb [hunk 1]
```diff
@@ -85,18 +85,33 @@ def guest_user
...
-
     respond_to do |format|
-      format.json { render json: config }
+      format.json { render json: viewer_config_value(resource) }
     end
   end
 
+  def viewer_config_value(resource)
+    return default_uv_config if full_viewer_capability?(resource)
+    downloads_disabled_uv_config.tap do |config|
```
Comment (hackmastera) [inline app/controllers/application_controller.rb:95]: nice use of tap!
