### PR TITLE
Turn off search history when in read-only mode

### LINKED ISSUE #2875: read-only mode breaks searching
[Figgy/production] ActiveRecord::StatementInvalid: PG::InsufficientPrivilege: ERROR:  permission denied for relation searches: INSERT INTO "searches" ("query_params", "created_at", "updated_at") VALUES ($1, $2, $3) RETURNING "id"

## Backtrace

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/48219303)

### PR DESCRIPTION
**Pull request by hackmastera**
This allows people to search in read-only mode without getting errors
due to blacklight creating `Search` objects.

fixes #2875

### CODE REVIEW

**Comment by hackmastera** [comment]
Hm. Do not merge it looks like there's another problem here, where the prev / next buttons will still cause errors.

File: spec/controllers/catalog_controller_spec.rb [hunk 1]
```diff
@@ -215,6 +215,24 @@
       get :index, params: { q: "" }
       expect(response).to be_success
     end
+
+    # rubocop:disable RSpec/AnyInstance
+    context "in read-only mode" do
+      let(:emsg) { "PG::InsufficientPrivilege: ERROR:  permission denied for relation searches" }
+      before do
+        allow(Figgy).to receive(:read_only_mode).and_return(true)
+        allow_any_instance_of(Blacklight::SearchContext).to receive(:find_or_initialize_search_session_from_params).and_raise ActiveRecord::StatementInvalid, emsg
```
Comment (eliotjordan) [inline spec/controllers/catalog_controller_spec.rb]: Is there a way to do this without `allow_any_instance`, or is there to too much mocking involved? FWIW, I was just poking around blacklight and was astounded by how many levels of nested concerns there are in the controller.

**Comment by hackmastera** [comment]
@eliotjordan I just pushed up something better (deals with the problem closer to the error) which also happens to address your concern!
