### PR TITLE
Handle archival object not being found

### LINKED ISSUE #4658: Handle an archival object not being found when trying to synchronize a DAO.
Throw an error if you can't find an archival object, rescue that error in the job and write to the log.

## Backtrace

    line 40 of [PROJECT_ROOT]/app/services/dao_updater.rb: create_digital_object
    line 15 of [PROJECT_ROOT]/app/services/dao_updater.rb: update!
    line 6 of [PROJECT_ROOT]/app/jobs/update_dao_job.rb: perform

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/81340297)

## Job Params
```ruby
{
  "context" => "Job raised exception",
  "job" => {
    "class" => "ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper",
    "wrapped" => "UpdateDaoJob",
    "queue" => "default",
    "args" => [{
      "job_class" => "UpdateDaoJob",
      "job_id" => "4672d0de-3c0b-48ae-bed0-cd30fbb1180a",
      "provider_job_id" => nil,
      "queue_name" => "default",
      "priority" => nil,
      "arguments" => ["a7033307-44aa-4877-9c01-a36f14c0c826"],
      "executions" => 0,
      "locale" => "en"
    }],
    "retry" => true,
    "jid" => "d04c58b187cbb77189ddecd9",
    "created_at" => 1631294581.2601366,
    "enqueued_at" => 1632733132.507099,
    "error_message" => "undefined method `repository_id' for nil:NilClass",
    "error_class" => "NoMethodError",
    "failed_at" => 1631294767.4257739,
    "retry_count" => 24,
    "retried_at" => 1632733136.5631227
  },
  "jobstr" => "{\"class\":\"ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper\",\"wrapped\":\"UpdateDaoJob\",\"queue\":\"default\",\"args\":[{\"job_class\":\"UpdateDaoJob\",\"job_id\":\"4672d0de-3c0b-48ae-bed0-cd30fbb1180a\",\"provider_job_id\":null,\"queue_name\":\"default\",\"priority\":null,\"arguments\":[\"a7033307-44aa-4877-9c01-a36f14c0c826\"],\"executions\":0,\"locale\":\"en\"}],\"retry\":true,\"jid\":\"d04c58b187cbb77189ddecd9\",\"created_at\":1631294581.2601366,\"enqueued_at\":1632733132.507099,\"error_message\":\"undefined method `repository_id' for nil:NilClass\",\"error_class\":\"NoMethodError\",\"failed_at\":1631294767.4257739,\"retry_count\":23,\"retried_at\":1632452739.514128}"
}
```

## Full Trace
```
/opt/figgy/releases/20210921145911/app/services/dao_updater.rb:40:in `create_digital_object'
/opt/figgy/releases/20210921145911/app/services/dao_updater.rb:15:in `update!'
/opt/figgy/releases/20210921145911/app/jobs/update_dao_job.rb:6:in `perform'
/opt/figgy/shared/bundle/ruby/2.6.0/gems/activejob-5.2.5/lib/active_job/execution.rb:39:in `block in perform_now'
/opt/figgy/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.5/lib/active_support/callbacks.rb:109:in `block in run_callbacks'
/opt/figgy/shared/bundle/ruby/2.6.0/gems/i18n-0.9.5/lib/i18n.rb:268:in `with_locale'
/opt/figgy/shared/bundle/ruby/2.6.0/gems/activejob-5.2.5/lib/active_job/translation.rb:9:in `block (2 levels) in <module:Translation>'
/opt/figgy/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.5/lib/active_support/callbacks.rb:118:in `instance_exec'
/opt/figgy/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.5/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
/opt/figgy/shared/bundle/ruby/2.6.0/gems/activejob-5.2.5/lib/active_job/logging.rb:26:in `block (4 levels) in <module:Logging>'
/opt/figgy/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.5/lib/active_support/notifications.rb:168:in `block in instrument'
/opt/figgy/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.5/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
/opt/figgy/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.5/lib/active_support/notifications.rb:168:in `instrument'
/opt/figgy/shared/bundle/ruby/2.6.0/gems/activejob-5.2.5/lib/active_job/logging.rb:25:in `block (3 levels) in <module:Logging>'
/opt/figgy/shared/bundle/ruby/2.6.0/gems/activejob-5.2.5/lib/active_job/logging.rb:46:in `block in tag_logger'
/opt/figgy/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.5/lib/active_support/tagged_logging.rb:71:in `block in tagged'
/opt/figgy/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.5/lib/active_support/tagged_logging.rb:28:in `tagged'
/opt/figgy/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.5/lib/active_support/tagged_logging.rb:71:in `tagged'
/opt/figgy/shared/bundle/ruby/2.6.0/gems/activejob-5.2.5/lib/active_job/logging.rb:46:in `tag_logger'
/opt/figgy/shared/bundle/ruby/2.6.0/gems/activejob-5.2.5/lib/active_job/logging.rb:22:in `block (2 levels) in <module:Logging>'
/opt/figgy/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.5/lib/active_support/callbacks.rb:118:in `instance_exec'
/opt/figgy/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.5/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
/opt/figgy/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.5/lib/active_support/callbacks.rb:136:in `run_callbacks'
/opt/figgy/shared/bundle/ruby/2.6.0/gems/activejob-5.2.5/lib/active_job/execution.rb:38:in `perform_now'
/opt/figgy/shared/bundle/ruby/2.6.0/gems/activejob-5.2.5/lib/active_job/execution.rb:24:in `block in execute'
/opt/figgy/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.5/lib/active_support/callbacks.rb:109:in `block in run_callbacks'
/opt/figgy/shared/bundle/ruby/2.6.0/gems/activejob-5.2.5/lib/active_job/railtie.rb:28:in `block (4 levels) in <class:Railtie>'
/opt/figgy/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.5/lib/active_support/execution_wrapper.rb:87:in `wrap'
/opt/figgy/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.5/lib/active_support/reloader.rb:73:in `block in wrap'
/opt/figgy/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.5/lib/active_support/execution_wrapper.rb:83:in `wrap'
/opt/figgy/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.5/lib/active_support/reloader.rb:72:in `wrap'
/opt/figgy/shared/bundle/ruby/2.6.0/gems/activejob-5.2.5/lib/active_job/railtie.rb:27:in `block (3 levels) in <class:Railtie>'
/opt/figgy/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.5/lib/active_support/callbacks.rb:118:in `instance_exec'
/opt/figgy/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.5/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
/opt/figgy/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.5/lib/active_support/callbacks.rb:136:in `run_callbacks'
/opt/figgy/shared/bundle/ruby/2.6.0/gems/activejob-5.2.5/lib/active_job/execution.rb:22:in `execute'
/opt/figgy/shared/bundle/ruby/2.6.0/gems/activejob-5.2.5/lib/active_job/queue_adapters/sidekiq_adapter.rb:42:in `perform'
/opt/figgy/shared/bundle/ruby/2.6.0/gems/sidekiq-5.0.4/lib/sidekiq/processor.rb:199:in `execute_job'
/opt/figgy/shared/bundle/ruby/2.6.0/gems/sidekiq-5.0.4/lib/sidekiq/processor.rb:170:in `block (2 levels) in process'
/opt/figgy/shared/bundle/ruby/2.6.0/gems/sidekiq-5.0.4/lib/sidekiq/middleware/chain.rb:128:in `block in invoke'
/opt/figgy/shared/bundle/ruby/2.6.0/gems/ddtrace-0.16.0/lib/ddtrace/contrib/sidekiq/tracer.rb:37:in `block in call'
/opt/figgy/shared/bundle/ruby/2.6.0/gems/ddtrace-0.16.0/lib/ddtrace/tracer.rb:296:in `trace'
/opt/figgy/shared/bundle/ruby/2.6.0/gems/ddtrace-0.16.0/lib/ddtrace/contrib/sidekiq/tracer.rb:29:in `call'
/opt/figgy/shared/bundle/ruby/2.6.0/gems/sidekiq-5.0.4/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/opt/figgy/shared/bundle/ruby/2.6.0/gems/sidekiq-pro-3.7.1/lib/sidekiq/batch/middleware.rb:54:in `call'
/opt/figgy/shared/bundle/ruby/2.6.0/gems/sidekiq-5.0.4/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/opt/figgy/shared/bundle/ruby/2.6.0/gems/honeybadger-4.8.0/lib/honeybadger/plugins/sidekiq.rb:10:in `call'
/opt/figgy/shared/bundle/ruby/2.6.0/gems/sidekiq-5.0.4/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/opt/figgy/shared/bundle/ruby/2.6.0/gems/sidekiq-5.0.4/lib/sidekiq/middleware/chain.rb:133:in `invoke'
/opt/figgy/shared/bundle/ruby/2.6.0/gems/sidekiq-5.0.4/lib/sidekiq/processor.rb:169:in `block in process'
/opt/figgy/shared/bundle/ruby/2.6.0/gems/sidekiq-5.0.4/lib/sidekiq/processor.rb:141:in `block (6 levels) in dispatch'
/opt/figgy/shared/bundle/ruby/2.6.0/gems/sidekiq-5.0.4/lib/sidekiq/job_retry.rb:97:in `local'
/opt/figgy/shared/bundle/ruby/2.6.0/gems/sidekiq-5.0.4/lib/sidekiq/processor.rb:140:in `block (5 levels) in dispatch'
/opt/figgy/shared/bundle/ruby/2.6.0/gems/sidekiq-5.0.4/lib/sidekiq/rails.rb:42:in `block in call'
/opt/figgy/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.5/lib/active_support/execution_wrapper.rb:87:in `wrap'
/opt/figgy/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.5/lib/active_support/reloader.rb:73:in `block in wrap'
/opt/figgy/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.5/lib/active_support/execution_wrapper.rb:87:in `wrap'
/opt/figgy/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.5/lib/active_support/reloader.rb:72:in `wrap'
/opt/figgy/shared/bundle/ruby/2.6.0/gems/sidekiq-5.0.4/lib/sidekiq/rails.rb:41:in `call'
/opt/figgy/shared/bundle/ruby/2.6.0/gems/sidekiq-5.0.4/lib/sidekiq/processor.rb:136:in `block (4 levels) in dispatch'
/opt/figgy/shared/bundle/ruby/2.6.0/gems/sidekiq-5.0.4/lib/sidekiq/processor.rb:215:in `stats'
/opt/figgy/shared/bundle/ruby/2.6.0/gems/sidekiq-5.0.4/lib/sidekiq/processor.rb:131:in `block (3 levels) in dispatch'
/opt/figgy/shared/bundle/ruby/2.6.0/gems/sidekiq-5.0.4/lib/sidekiq/job_logger.rb:7:in `call'
/opt/figgy/shared/bundle/ruby/2.6.0/gems/sidekiq-5.0.4/lib/sidekiq/processor.rb:130:in `block (2 levels) in dispatch'
/opt/figgy/shared/bundle/ruby/2.6.0/gems/sidekiq-5.0.4/lib/sidekiq/job_retry.rb:72:in `global'
/opt/figgy/shared/bundle/ruby/2.6.0/gems/sidekiq-5.0.4/lib/sidekiq/processor.rb:129:in `block in dispatch'
/opt/figgy/shared/bundle/ruby/2.6.0/gems/sidekiq-5.0.4/lib/sidekiq/logging.rb:44:in `with_context'
/opt/figgy/shared/bundle/ruby/2.6.0/gems/sidekiq-5.0.4/lib/sidekiq/logging.rb:38:in `with_job_hash_context'
/opt/figgy/shared/bundle/ruby/2.6.0/gems/sidekiq-5.0.4/lib/sidekiq/processor.rb:128:in `dispatch'
/opt/figgy/shared/bundle/ruby/2.6.0/gems/sidekiq-5.0.4/lib/sidekiq/processor.rb:168:in `process'
/opt/figgy/shared/bundle/ruby/2.6.0/gems/sidekiq-5.0.4/lib/sidekiq/processor.rb:85:in `process_one'
/opt/figgy/shared/bundle/ruby/2.6.0/gems/sidekiq-5.0.4/lib/sidekiq/processor.rb:73:in `run'
/opt/figgy/shared/bundle/ruby/2.6.0/gems/sidekiq-5.0.4/lib/sidekiq/util.rb:16:in `watchdog'
/opt/figgy/shared/bundle/ruby/2.6.0/gems/sidekiq-5.0.4/lib/sidekiq/util.rb:25:in `block in safe_thread'
```

### PR DESCRIPTION
**Pull request by zaymasood**
closes #4658

### CODE REVIEW

File: app/services/aspace/client.rb [hunk 1]
```diff
@@ -20,6 +22,7 @@ def find_archival_object_by_component_id(component_id:)
       # Check every repository, we don't store things by repository in Figgy.
       repositories.each do |repository|
         archival_object = get("#{repository['uri']}/find_by_id/archival_objects?ref_id[]=#{component_id}").parsed
+        raise ArchivalObjectNotFound if archival_object.empty?
```
Comment (hackartisan) [inline app/services/aspace/client.rb:25]: I think we should add the component_id to the error message here.

File: app/jobs/update_dao_job.rb [hunk 2]
```diff
@@ -4,6 +4,8 @@ class UpdateDaoJob < ApplicationJob
   def perform(id)
     change_set = ChangeSet.for(change_set_persister.metadata_adapter.query_service.find_by(id: id))
     DaoUpdater.new(change_set: change_set, change_set_persister: change_set_persister).update!
+  rescue Aspace::Client::ArchivalObjectNotFound => error
+    Rails.logger.error("Archival object not found: #{error}")
```
Comment (hackartisan) [inline app/jobs/update_dao_job.rb:8]: Let's also log the resource id here.

**Review by hackartisan — CHANGES_REQUESTED** [review]
I think when we get the log message we'll want the resource id and the component id so let's add those.

**Review by hackartisan — APPROVED** [review]
looks great!
