### PR TITLE
Don't set a blank Last-modified header

### LINKED ISSUE #143: Downloading files not working in staging.

### PR DESCRIPTION
**Pull request by escowles**
Fixes #143

### CODE REVIEW

File: valhalla/app/controllers/valhalla/downloads_controller.rb [hunk 1]
```diff
@@ -51,7 +51,7 @@ def prepare_file_headers
     response.headers['Content-Type'] = file_desc.mime_type.first.to_s
     response.headers['Content-Length'] ||= binary_file.size.to_s
     # Prevent Rack::ETag from calculating a digest over body
-    response.headers['Last-Modified'] = modified_date
+    response.headers['Last-Modified'] = modified_date if modified_date
```
Comment (tpendragon) [inline valhalla/app/controllers/valhalla/downloads_controller.rb]: It's super weird this is blank, I wonder if there's a bug.

Comment (escowles) [reply valhalla/app/controllers/valhalla/downloads_controller.rb]: Agreed, I just created #344 to figure out why it's blank.
