### PR TITLE
Extending BulkIngestController in order to handle the bulk creation of resources using files downloaded from a cloud storage provider

### LINKED ISSUE #2274: BulkIngestService should handle Folders from cloud storage providers (e. g. Google Drive)
## Backtrace

    line 44 of [PROJECT_ROOT]/app/services/bulk_ingest_service.rb: attach_dir
    line 13 of [PROJECT_ROOT]/app/jobs/ingest_folder_job.rb: block in perform
    line 113 of [PROJECT_ROOT]/app/change_set_persisters/change_set_persister.rb: block (2 levels) in buffer_into_index

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/42330874)

### PR DESCRIPTION
**Pull request by jrgriffiniii**
Resolves #2274

### CODE REVIEW

**Comment by jrgriffiniii** [comment]
I apologize for that, I was able to reproduce the errors, https://github.com/pulibrary/figgy/pull/2323/commits/80de5fe6c0295be70f6889708c4f714ad99ecfcb should resolve those.

However, I still need to also address some behavior I've found with supporting MVW's in bulk ingestion.

File: spec/controllers/bulk_ingest_controller_spec.rb [hunk 1]
```diff
@@ -82,6 +109,69 @@
       end
     end
 
+    context "with files hosted on a cloud-storage provider" do
+      let(:selected_files) do
+        {
+          "0" => { "url" => "https://www.cloud.com/files/1.tif?alt=media", "file_name" => "1.tif", "file_size" => "100", "auth_header" => { "Authorization" => "Bearer secret" } },
+          "1" => { "url" => "https://www.cloud.com/files/2.tif?alt=media", "file_name" => "2.tif", "file_size" => "100", "auth_header" => { "Authorization" => "Bearer secret" } }
```
Comment (escowles) [inline spec/controllers/bulk_ingest_controller_spec.rb]: I know these URLs won't be retrieved because the BrowseEverythingJob is stubbed, but can you change them to use `example.com`?
