### PR TITLE
Fix display of fixity checks from deleted resources.

### LINKED ISSUE #3814: Fixity Dashboard should render if there are events pointing to deleted resources
In staging there are events for resources that have since been deleted. This is okay - we keep events around because you can bring the object back from the dead if it was preserved, but the table should still render. We can just add some null checks to the table.

## Backtrace

    line 13 of [PROJECT_ROOT]/app/views/fixity_dashboard/_cloud_fixity_table.html.erb: block in _app_views_fixity_dashboard__cloud_fixity_table_html_erb__3972264412316033458_69912600229460
    line 11 of [PROJECT_ROOT]/app/views/fixity_dashboard/_cloud_fixity_table.html.erb: each
    line 11 of [PROJECT_ROOT]/app/views/fixity_dashboard/_cloud_fixity_table.html.erb: _app_views_fixity_dashboard__cloud_fixity_table_html_erb__3972264412316033458_69912600229460

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/62967771)

### PR DESCRIPTION
**Pull request by tpendragon**
Makes fixity dashboard display again.

Closes #3814

### CODE REVIEW

File: spec/features/fixity_dashboard_spec.rb [hunk 1]
```diff
@@ -32,6 +32,22 @@
     end
   end
 
+  context "the fixity check for a resource by a cloud service provider is for a deleted resource" do
+    it "displays that the event was a failure" do
```
Comment (hackartisan) [inline spec/features/fixity_dashboard_spec.rb:36]: How does this test check that it's in the failure table?

It seems to check for the text "SUCCESS" which is confusing given the title of the test.

**Review by hackartisan — CHANGES_REQUESTED** [review]

File: spec/features/fixity_dashboard_spec.rb (hunk 1 above)
Comment (tpendragon) [reply spec/features/fixity_dashboard_spec.rb]: @hackartisan Thanks for the catch! Fixed.

**Review by hackartisan — APPROVED** [review]
👍 🎉
