### PR TITLE
rescue FileNotFound in CreateDerivatesJob

### LINKED ISSUE #4643: CreateDerivativesJob should rescue Valkyrie::StorageAdapter::FileNotFound and not retry.
## Backtrace

    line 27 of [PROJECT_ROOT]/app/storage_adapters/instrumented_storage_adapter.rb: block in find_by
    line 48 of [PROJECT_ROOT]/app/storage_adapters/instrumented_storage_adapter.rb: block in trace
    line 43 of [PROJECT_ROOT]/app/storage_adapters/instrumented_storage_adapter.rb: trace

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/79895482)

## Notes

This job sends us an error sometimes if someone deletes the file before Sidekiq catches up. We should just rescue FileNotFound and make sure it both doesn't send us a honeybadger error and doesn't retry.

### PR DESCRIPTION
**Pull request by XanderGardner**
closes #4643

### CODE REVIEW

File: spec/jobs/create_derivatives_job_spec.rb [hunk 1]
```diff
@@ -4,15 +4,13 @@
 RSpec.describe CreateDerivativesJob do
   let(:derivatives_service) { instance_double(Valkyrie::Derivatives::DerivativeService) }
   let(:file_set) { FactoryBot.create_for_repository(:file_set) }
-  let(:fixity_job) { instance_double(CheckFixityJob) }
```
Comment (hackartisan) [inline spec/jobs/create_derivatives_job_spec.rb:7]: Why don't we need this anymore? And/or why did we need it initially?

**Review by hackartisan — CHANGES_REQUESTED** [review]

File: spec/jobs/create_derivatives_job_spec.rb (hunk 1 above)
Comment (XanderGardner) [reply spec/jobs/create_derivatives_job_spec.rb:7]: It was initially used to test that the CheckFixityJob received perform_later. This was replaced with checking for an enqueued CheckFixityJob https://github.com/pulibrary/figgy/commit/6c7b65b7f21724ec180dc07e62de9edc6d3576bd

**Review by hackartisan — APPROVED** [review]

File: spec/jobs/create_derivatives_job_spec.rb (hunk 1 above)
Comment (hackartisan) [reply spec/jobs/create_derivatives_job_spec.rb:7]: I see, thank you! And thanks for cleaning it up.

**Review by eliotjordan — APPROVED** [review]
